services:
  # app:
  #   build: crm-platform
  #   ports:
  #     - 8000:8000

  postgres:
    image: 'postgres:16'
    container_name: 'postgres-db'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: