services:
  web:
    build: crm_platform
    container_name: crm_platform
    command: gunicorn crm_platform.wsgi:application --bind 0.0.0.0:8000 --workers=3
    volumes:
      - static_data:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: 'postgres:16'
    container_name: 'postgres-db'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
  static_data: